defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 802c9eab-6bb4-4618-b8e1-35ae17d0146e # Page
handle: pages
maxAuthors: 1
minAuthors: 0
name: Pages
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  5cc20a1d-c8ff-42b1-8fa7-2da05645834a: # Rias.be
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: '{parent.uri}/{slug}'
structure:
  maxLevels: null
  uid: 0421e0ae-124b-4bc3-9cc6-803681e87bee
type: structure
